package student_yevgeniy_tolks.lesson_13_exceptions.level_3.task20;

class MultiCatchExample {
    public static void main(String[] args) {
        try {

        } catch (Exception e) {
//
//        } catch (ArithmeticException a) {   // this exception already caught, should be deleted,
//                                            // because this class extends RuntimeException
//                                            // RuntimeException extends Exception
        }
    }
}
